apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  namespace: mvpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotes
    spec:
      containers:
      - image: acrmvpapptestwesteurope.azurecr.io/quotes:1.0.0
        name: quotes
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false