apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: mvpapp
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer