apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed
  namespace: mvpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsfeed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: newsfeed
    spec:
      containers:
      - image: acrmvpapptestwesteurope.azurecr.io/newsfeed:1.0.0
        name: newsfeed
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false